### ISSUE TITLE
Removal of `isOpen`?

### ISSUE THREAD

**Issue by STRML** [tajo/react-portal#121] opened 2016-12-29 23:18 UTC
Related to [this comment](https://github.com/tajo/react-portal/pull/82#issuecomment-269700457), I always thought it odd that this component had a property `isOpen` for conditional rendering, when developers are capable of managing that themselves:

```jsx
return (
  <div>
    <button onClick={() => this.setState({opened: !this.state.opened})}>Toggle</button>
    {this.state.opened ? 
      <Portal><div>Portal Contents</div></Portal>
    : null}
  </div>
);
```

Ideally, the user should manage the state themselves and Portal should have no state.

Existing helpers like `closeOnEsc` should then only call the `onClose` callback, and not actually close the portal unless the developer desires.

This also solves a few bugs, like the following:

* Create Portal with `isOpen={true}` and `closeOnEsc={true}`
* User presses esc, closing the portal
* Portal's containing component rerenders for any reason, causing `componentWillReceiveProps` to be called
* Portal unexpectedly re-opens 

To ease the transition, perhaps it would make sense to ship a wrapper component that manages this state for you for common cases. This is similar to what I have done in other projects with [`<Resizable>`/`<ResizableBox>`](https://github.com/STRML/react-resizable#react-resizable) and [`<Draggable>`/`<DraggableCore>`](https://github.com/mzabriskie/react-draggable), which has worked nicely.

Said stateless component would also serve as a very low-overhead building block for other components.

**Comment by tajo** [comment] 2016-12-30 00:14
I like this idea a lot. A wrapper component is must have.

It makes the library more readable and nicely separates controlled (stateless component) and uncontrolled (wrapper component) approaches.

The problem is, this means to do a complete rewrite.

**Comment by evandavis** [comment] 2017-03-09 15:47
> The problem is, this means to do a complete rewrite.

I think you might be able to do this by just taking all of the state and moving it to an HOC, and export both. That way it's an upgrade, not a rewrite. I'd be willing to start a PR if that's something you're interested in.

**Comment by tajo** [comment] 2017-03-09 18:20
@evandavis Yes, please! That's exactly what I want to do. Ideally, it should still pass all (or most of) current tests.

**Comment by STRML** [comment] 2017-05-11 22:13
See https://github.com/STRML/react-portal-minimal - I have not yet built the compatibility layer, but [as you can see](https://github.com/STRML/react-portal-minimal/blob/af03ed5c6f31e752369f0c70ca4cd5b6ccd2f752/lib/portal.js) the project is much simpler without the state.

**Comment by tajo** [comment] 2017-10-01 21:31
Removed:  https://github.com/tajo/react-portal/issues/157

**Closed by tajo** 2017-10-01 21:31 UTC
Labels: enhancement
